Fix missing return type for `void` method
Resolves the following error message:
```
Build started, please wait...
Robot.cs(34,16): error CS1520: Method must have a return type
[/app/ToyRobot/Main.csproj]
```